### PR TITLE
Move common methods to `Repository` module

### PR DESCRIPTION
**Pull request by joelvh**
Hi @paneq, would you accept some updates to share logic across `EventRepository` implementations?

I'm working on the ROM-based repository adapter ([feature/rom_adapter](https://github.com/joelvh/rails_event_store/tree/feature/rom_adapter)) and was looking to find ways to share code a bit more. I think that there can be more sharing between AR and ROM as well.

Let me know your thoughts on this.

Thanks.

~Joel

### CODE REVIEW

**Comment by paneq** [comment]
@joelvh 

> would you accept some updates to share logic across EventRepository implementations?

I think we would however as always there are some gotchas / concerns to think about :)

a) is `InMemoryRepository` using this method? Nope? Perhpas it does not need to be shared? 

`InMemoryRepository`, `RailsEventStoreActiveRecord::EventRepository` and your repository could use a certain method ? That's a good sign to extract.

b) you wanted to for example extract:

```
+    def append_to_stream(events, stream_name, expected_version)
+      add_to_stream(events, stream_name, expected_version, true)
+    end
+
+    def link_to_stream(events, stream_name, expected_version)
+      add_to_stream(events, stream_name, expected_version, nil)
+    end
+  
+  private
+
+    def add_to_stream(events, stream_name, expected_version, include_global, &block)
```

sure, why not. But the truth is... We don't like the fact that `add_to_stream` takes `true` or `nil` as arugment and so many parameters. So I would not want to encourage other repository authors to go the same way. Maybe you/they figure out something more pretty and we could port back a nicer solution to our implementation.

c) `normalize_to_array` is extracted as a method only to avoid issues with a bug in mutant: https://github.com/mbj/mutant/issues/724 and it is skipped from mutations.

d) `normalize_expected_version` looks like a good candidate for extraction.

e) Some tests and mutation tests are failing so we cannot accept it.

f) Here is my guideline for you. 

* Start by copy-pasting `RailsEventStoreActiveRecord::EventRepository` into a new file/class. I suggest inlining code delegated to `EventRepositoryReader`
* Method by method change ActiveRecord calls into ROM calls. 
* Keep the tests green. You already know how to use the tests we already have.
* Commit often. That way you will see progress.
* When you eliminate all ActiveRecord usage, drop activerecord dependency from your library.
* Refactor whenever you want when you are in green.
* At the end of the process see if there is any shared code between your implementation and our implementation. If there is, create a PR suggesting to extract it, to make it shareable. If there is not, then problem solved, there is nothing you needed from us in the first place :)

What do you think about such approach?

**Comment by paneq** [comment]
> It was interesting to see how the "reader" is used in the AR repository because it's more similar to how ROM thinks about a repository.

Just be aware that with fluent-api for reading #184 that we want to introduce soon we might change the repository implementation for reading events to:

```
def read(specification)
end
```

as all those reading methods are very similar, almost identical and with confusingly similar names :)

> In the meantime, do you suggest I fix the tests for this PR or close it?

let's close it, and we will revisit what can be easily shared once you have a working repository. Waiting eagerly to see it.

**Comment by joelvh** [comment]
@paneq Good to know the Reader is on your radar. I definitely have some thoughts on this. I will start by getting the ROM implementation working. You can see that I've implemented 2 ROM repositories, and am just working on getting all tests to pass: https://github.com/joelvh/rails_event_store/blob/feature/rom_adapter/ruby_event_store_rom_sql/lib/ruby_event_store_rom_sql/event_repository.rb

**Comment by joelvh** [comment]
@paneq quick question - how do you run tests and mutations locally?

**Comment by paneq** [comment]
@joelvh 

* https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/Makefile#L15
* https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/Makefile#L19
* https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/Makefile#L26
* what CI does (includes connection strings) : https://github.com/RailsEventStore/rails_event_store/blob/master/.travis.yml

**Comment by joelvh** [comment]
OK, I found the commands that were failing - so it's running each by hand. Wasn't sure if you used CI locally.

Thanks!

**Pull request closed without merging**
