### PR TITLE
Bump to mutant ~> 0.10.13

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mbj** [comment]
@pawelpacana the coverage criteria are now working for the aggregate root, but for some reason `mutate_rails_event_store_rspec_ruby_2_7` is acting if they where not present.

I'll still have to debug this case.

**Comment by pawelpacana** [comment]
Failure expected:
- there are some one-off uncovered additions still to be dealt with
- `rails_event_store-rspec` behaves differently on linux vs macos regarding mutation

What was not expected:
- seeing hanging build of `aggregate_root`: https://app.circleci.com/pipelines/github/RailsEventStore/rails_event_store/1204/workflows/8efa4e4d-aa26-4ccf-bc6d-ebdff414d0db/jobs/66085

**Comment by pawelpacana** [comment]
That one is unexpected too: https://app.circleci.com/pipelines/github/RailsEventStore/rails_event_store/1204/workflows/8efa4e4d-aa26-4ccf-bc6d-ebdff414d0db/jobs/66090

```
progress: 11153/11569 alive: 26 runtime: 1994.32s killtime: 1475.28s mutations/s: 5.59
#<Thread:0x00005597d856a8e0 /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:20 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	20: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:21:in `call'
	19: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:21:in `loop'
	18: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:26:in `block in call'
	17: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:26:in `call'
	16: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/env.rb:57:in `kill'
	15: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/env.rb:136:in `run_mutation_tests'
	14: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:232:in `call'
	13: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `with'
	12: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `pipe'
	11: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:46:in `block in with'
	10: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:233:in `block in call'
	 9: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `with'
	 8: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `pipe'
	 7: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:46:in `block in with'
	 6: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:234:in `block (2 levels) in call'
	 5: from /usr/local/bundle/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
	 4: from /usr/local/bundle/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
	 3: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:86:in `call'
	 2: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:123:in `read_child_result'
	 1: from /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:148:in `read_targets'
/usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:148:in `select': Bad address (Errno::EFAULT)
bundler: failed to load command: mutant (/usr/local/bundle/bin/mutant)
Errno::EFAULT: Bad address
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:148:in `select'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:148:in `read_targets'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:123:in `read_child_result'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:86:in `call'
  /usr/local/bundle/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
  /usr/local/bundle/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:234:in `block (2 levels) in call'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:46:in `block in with'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `pipe'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `with'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:233:in `block in call'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:46:in `block in with'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `pipe'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:45:in `with'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/isolation/fork.rb:232:in `call'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/env.rb:136:in `run_mutation_tests'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/env.rb:57:in `kill'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:26:in `call'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:26:in `block in call'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:21:in `loop'
  /usr/local/bundle/gems/mutant-0.10.13/lib/mutant/parallel/worker.rb:21:in `call'
make: *** [../support/make/mutant.mk:3: mutate] Error 1
make: Leaving directory '/root/project/ruby_event_store'
```

**Comment by mbj** [comment]
@pawelpacana This smells like another MRI fault. I suspect MRI will never be stable under threads + high volume of fork calls.

all these code path will be gone with the new master process written in haskell. Its a hard tie for me if I should focus there or put more workarounds in. We'll see.

**Comment by pawelpacana** [comment]
> all these code path will be gone with the new master process written in haskell. Its a hard tie for me if I should focus there or put more workarounds in. We'll see.

Going incremental might reduce the chance for MRI to crash. In the past we were also running mutant on macos to minimize this impact of MRI. Hanging mutations happened over several MRI Ruby versions so far, hard to be optimistic about new ones.

It would be splendid to have issue with `rails_event_store-rspec` covered. That would mean parity in running mutant on MRI 2.6. 

I really hoped external timeouts would put an end to this hanging builds misery. If it doesn't work and working around MRI has marginal effect, focusing on new master process seems reasonable.

**Comment by mbj** [comment]
@pawelpacana We've got a stable reproduction, I'm not willing to give up easily.

I've commercially during consultant done more "hand nurturing" of MRI on complex IO patterns than visible in mutant, there are still cards to play. 

Stable reproduction lets me believe that external timeouts actually improved the situation.

**Comment by pawelpacana** [comment]
Retry did not hang, merging does not make it worse

**Pull request merged**
