### PR TITLE
Use exact Rails version in test dummy apps

### PR DESCRIPTION
**Pull request by mpraglowski**
Fix for #193

### CODE REVIEW

**Comment by pawelpacana** [comment]
On the side you could follow: f866e07c046f2b67443b89913edc485318a538eb and rename `dummy_5_1_4` to `dummy_5_1` so that we test latest released bugfix version of given minor.

**Comment by mpraglowski** [comment]
yeah,, maybe that better approach, and we should add 5.2 version

**Comment by paneq** [comment]
> we should add 5.2 version

not yet released but we could

**Comment by mpraglowski** [comment]
The approach with testing latest version within Rails minor version implemented here in #253. Closing this one.

**Pull request closed without merging**
