### PR TITLE
Value based offset

### PR DESCRIPTION
**Pull request by porbas**
Hi @mpraglowski 
I've closed #746 as it was really messed up with commits, merges and rebases. Here is clean commits history.

### CODE REVIEW

**Comment by mpraglowski** [comment]
@porbas could you make some benchmark of speed improvements? You could base the benchmark code on https://github.com/mlomnicki/res-benchmarks - with my changes in https://github.com/mlomnicki/res-benchmarks/pull/1 - but you will need to adjust the read code to make sure you check reading in batches on a large set of domain events.

**Comment by porbas** [comment]
Yes, I've already started working on benchmarks but it is not easy to set up. Thanks for links. I hope it will be easier now!

**Comment by mpraglowski** [comment]
You could also use https://github.com/RailsEventStore/rails_event_store/tree/master/contrib/measure to build your benchmark code.

**Comment by porbas** [comment]
Benchmark prepared https://github.com/porbas/res-benchmarks and executed for 200_000 events (PostgreSQL 12):
```
Benchmarking master
Calculating -------------------------------------
              master      0.006  (± 0.0%) i/s -      1.000  in 166.054008s
Benchmarking value_based_offset
Calculating -------------------------------------
  value_based_offset      0.008  (± 0.0%) i/s -      1.000  in 126.368918s

Comparison:
  value_based_offset:        0.0 i/s
              master:        0.0 i/s - 1.31x  (± 0.00) slower

```
it took about 20minutes to complete.

Now I'm going to run benchmark for 600_000 events

**Comment by porbas** [comment]
Benchmarks for 600_000 events took about 75 minutes. Now difference is about 2x:
```Benchmarking master
Calculating -------------------------------------
              master      0.001  (± 0.0%) i/s -      1.000  in 925.651214s
Benchmarking value_based_offset
Calculating -------------------------------------
  value_based_offset      0.002  (± 0.0%) i/s -      1.000  in 447.880005s

Comparison:
  value_based_offset:        0.0 i/s
              master:        0.0 i/s - 2.07x  (± 0.00) slower

real	74m59,886s
user	45m48,459s
sys	1m56,759s
```

**Comment by porbas** [comment]
This is just friendly reminder :smiley:

**Comment by pawelpacana** [comment]
Good to base to improve upon, thanks!

**Pull request merged**
