### PR TITLE
Communicate event_id along EventDuplicatedInStream

### PR DESCRIPTION
**Pull request by pawelpacana**
[#440]

### CODE REVIEW

**Comment by pawelpacana** [comment]
@joelvh any ideas on passing `event_id` of violated constraint to https://github.com/RailsEventStore/rails_event_store/blob/c05d64db8eac6eb6778ab4627e2e7c957ea179ce/ruby_event_store-rom/lib/ruby_event_store/rom/event_repository.rb#L24?

**Comment by joelvh** [comment]
Oh boy.... Will take a look.

**Comment by joelvh** [comment]
@pawelpacana made an update to pass the `event_id` for application-level uniqueness exceptions. However, I'm not sure how to do this for database-level errors because the inserts are done in batches, not per-event. Do you know if there's a way to get the database to include the violation values in the error message?

**Comment by pawelpacana** [comment]
> I'm not sure how to do this for database-level errors because the inserts are done in batches, not per-event. 

I believe there's no need to do that on database-level (if I understand that term correctly). We do insert in batches, but as a one transaction —https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L69-L88. A single uniqueness violation is enough to roll it back.

> Do you know if there's a way to get the database to include the violation values in the error message?

Each RDBMS may implement it differently so we'd have to check all of the supported ones. I haven't checked so far if you get a list or just a one value of a row that didn't meet the constraint. I think we don't have to do that.

**Pull request closed without merging**
