### PR TITLE
 Test agains rails 5.2 version

### LINKED ISSUE #252: Test agains rails 5.2 version

### PR DESCRIPTION
**Pull request by jandudulski**
I'm not sure about `rails_event_store-browser` specs. Why is there only a single, specific version in the Makefile? Are there any specs running for versions `4.2.10` and `5.0.6`?

Fixes #252

---
This change is [Reviewable](https://reviewable.io/reviews/railseventstore/rails_event_store/256)

### CODE REVIEW

**Comment by pawelpacana** [comment]
> Why is there only a single, specific version in the Makefile?

The one in `Makefile` is used specifically for mutation tests (https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store-browser/Makefile#L3). We limit mutation testing run to one chosen dependency version. Units on the other hand are tested against many combinations, as seen in `.travis.yml`.

**Comment by pawelpacana** [comment]
Regarding https://travis-ci.org/RailsEventStore/rails_event_store/jobs/360438409 and missing `bin/rails` -- binstubs need to be added with `-f` there as they're ignored in top-level `gitignore`.

**Comment by paneq** [comment]
Good progress. A few errors still occuring.

**Comment by jandudulski** [comment]
```
[4/4] Building fresh packages...
error /home/travis/build/RailsEventStore/rails_event_store/rails_event_store-browser/elm/node_modules/elm: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/travis/build/RailsEventStore/rails_event_store/rails_event_store-browser/elm/node_modules/elm
Output:
Error communicating with URL https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz Error: connect ETIMEDOUT 23.45.134.89:443
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [install] Error 1
make: Leaving directory `/home/travis/build/RailsEventStore/rails_event_store/rails_event_store-browser'
```

Is it often a case? :/

**Comment by paneq** [comment]
ugh, never seen it before. i recommend retrying this single job.

**Comment by pawelpacana** [comment]
Getting closer :)

One failure (in mutant) has been fixed in master -- https://travis-ci.org/RailsEventStore/rails_event_store/jobs/361800785. Rebasing or merging master to branch would solve it.

**Comment by pawelpacana** [comment]
And now this affects you: https://github.com/RailsEventStore/rails_event_store/issues/254

**Comment by jandudulski** [comment]
Any ideas how this is affected? https://travis-ci.org/RailsEventStore/rails_event_store/jobs/362484974

**Comment by pawelpacana** [comment]
Thanks!

**Pull request merged**
