### PR TITLE
Feature/rom update messages upsert

### PR DESCRIPTION
**Pull request by joelvh**
This adds `overwrite` capability to the ROM adapter. Supercedes #463 to use UPSERT instead of batch UPDATE statements.

### CODE REVIEW

**Comment by joelvh** [comment]
@paneq @pawelpacana how do we specify to install Sqlite 3.24+ on TravisCI for upsert capability?

**Comment by joelvh** [comment]
@paneq @pawelpacana saw that you're skipping tests for sqlite. Got things working and merging to master.

**Comment by pawelpacana** [comment]
> saw that you're skipping tests for sqlite. Got things working and merging to master

I'm glad it worked! There's an open issue to support sqlite (#446) which is why test might have been skipped.

We've moved most of the tests to CircleCI (some still left on TravisCI) and those run on docker images based on CircleCI ones. They have sqlite in version 3.16.2-5+deb9u1. If you know how to add sqlite 3.26 to Debian Stretch I could push new images.

**Comment by joelvh** [comment]
@pawelpacana Looks like they released support in v0.26.0 of AR Import (based on the comment on https://github.com/zdennis/activerecord-import/issues/540#issuecomment-427488408

I opted to detect whether Sqlite 3.24.0+ is being used, otherwise throw an exception when using the `overwrite` feature.

**Pull request merged**
