### PR TITLE
AggregateRoot + Protobuf

### PR DESCRIPTION
**Pull request by paneq**
Maybe fixes: #578 :)

### CODE REVIEW

**Comment by obahareth** [comment]
@paneq Thank you so much for the quick response and this PR, it works!

:shipit:

**Comment by pawelpacana** [comment]
Proto test in aggregate_root would be a good addition to this

**Comment by pawelpacana** [comment]
@paneq does protobuf require namespacing with dot, that is for example: `res_testing.SpanishInquisition`? That one would break in current AR implementation as we split namespaces by `::`.

**Comment by pawelpacana** [comment]
See #582

**Pull request merged**
