### PR TITLE
Skip missing attributes when encrypting/decrypting event's payload

### PR DESCRIPTION
**Pull request by mpraglowski**

### CODE REVIEW

**Comment by casiodk** [comment]
Perfect! :) Thanks

**Comment by casiodk** [comment]
Hi guys, any progress on this :)

**Comment by fidel** [comment]
@casiodk it's merged now, sorry for the wait

**Comment by casiodk** [comment]
Perfect, thanks a lot for the help :) Do you need to publish a new version of the gem before its available?

**Comment by fidel** [comment]
I'm not sure about the next release date. If you're in hurry, you can use particular ref from github in your Gemfile:
`gem 'rails_event_store', github: 'RailsEventStore/rails_event_store', ref: '00810b3'`

**Comment by casiodk** [comment]
I think I tried with my own fork, but there was some missing assets when using the ruby browser, and I couldn't make it work..?

**Comment by casiodk** [comment]
I think I read some where assets where precompiled in the gem release?

**Pull request merged**
