### PR TITLE
Allow using RES-AR without Rails

### PR DESCRIPTION
**Pull request by paneq**
`rails/generators` as optional dependency. Test of course is added.

### CODE REVIEW

**Comment by paneq** [comment]
Failing mutation testing right now because in-memory sqlite db is not shared between processes and the schema created in test setup is not available in the executed script.

Makefile uses `DATABASE_URL ?= sqlite3::memory:` and spec helper uses `ENV['DATABASE_URL']  ||= 'sqlite3:db.sqlite3'`.

**Comment by joelvh** [comment]
hi @paneq we were chatting on Slack recently about various levels of decoupling. Do you have someplace your plans/roadmap around this topic? I'm working on a res-rom-sql adapter, but am curious to see to what level this decoupling is a topic/priority for you guys.

Thanks!

**Comment by paneq** [comment]
@joelvh I am not sure I understand the question. It's almost done, this PR. That's just it. http://railseventstore.org/docs/without_rails/ I hope to merge it this week.

**Comment by joelvh** [comment]
@paneq I saw the title of this fly by and wondered if you have other decoupling you're working on. That page you linked gives an idea of what I was looking for. Thanks!

**Comment by paneq** [comment]
> if you have other decoupling you're working on

I am not sure there is a place for much more decouplings. Almost everything can be exchanged by passing a different class to a constructor.

```
module RailsEventStore
  class Client < RubyEventStore::Client
    def initialize(repository: RailsEventStoreActiveRecord::EventRepository.new,
                   event_broker: EventBroker.new(dispatcher: ActiveJobDispatcher.new),
                   page_size: PAGE_SIZE)
      capture_metadata = ->{ Thread.current[:rails_event_store] }
      super(repository: repository,
            event_broker: event_broker,
            page_size: page_size,
            metadata_proc: capture_metadata)
    end

  end
end
```

And other classes also take dependencies like that:

```
module RailsEventStoreActiveRecord
  class EventRepository
    def initialize(mapper: RubyEventStore::Mappers::Default.new)
```

```
module RubyEventStore
  module Mappers
    class Default
      def initialize(serializer: YAML, events_class_remapping: {})
```

```
module RubyEventStore
  module Mappers
    class Protobuf
      def initialize(event_id_getter: :event_id, events_class_remapping: {})
```

😄

**Comment by joelvh** [comment]
Yeah, the composability is great! Thanks.

**Pull request merged**
