### PR TITLE
Make projections faster by only reading Events that have handlers

### PR DESCRIPTION
**Pull request by Gordin**

### CODE REVIEW

**Comment by mpraglowski** [comment]
I have mixed feelings about that PR. It looks like a nice improvement but how it will work if someone uses the event type remapping feature we have implemented in `DefaultMapper`? 
The remapping of event type (event's class) is performed while reading from event repository by mapper. I have no problem when someone explicte uses the `of_type` method because it's his/hers responsibility to provide correct types... but here it will be easy to miss the use case when some events won't be ready due to remapping feature.
I.e. class `A` given in `when` method, but it's stored as `X` in `event_type` and is only remapped to `A` while reading from event repository. Now it will work correctly because `X` will be remapped to `A` before it is processed by projection. With filtering by event type events of type `X` won't be read and won't be processed.

**Comment by Gordin** [comment]
I didn't know about the remapping feature, I'll look into it ^^. Maybe I can just also include the events that will be mapped.

I was gonna ask if you have any idea why the mutation testing for this fails fails in the EncryptionMapper, but I'm guessing it could have something to do with the remapping as well. I'll try to fix this as well.

**Comment by pawelpacana** [comment]
> I was gonna ask if you have any idea why the mutation testing for this fails fails in the EncryptionMapper

Sorry for the trouble with EncryptionMapper, the reason for this is https://github.com/RailsEventStore/rails_event_store/issues/567

**Comment by pawelpacana** [comment]
@Gordin that issue with EncryptionMapper should be gone if you rebase with master

**Comment by pawelpacana** [comment]
Thank you! I've rebased your branch in #709 and this is now merged. 

Remapping is yet to be done, but we did not support it in Projection previously either (#710).

**Pull request closed without merging**
