### PR TITLE
Update rspec dependency

### PR DESCRIPTION
**Pull request by masylum**
This is not allowing us to upgrade to Rails 6 :grimacing:

### CODE REVIEW

**Comment by pawelpacana** [comment]
Is it the rspec or rspec-rails that needs to be bumped to 4.x release?

I don't see rspec 4.x release yet: https://rubygems.org/search?utf8=✓&query=rspec

**Comment by pawelpacana** [comment]
This is an excerpt from one of my projects:

```ruby
$ ag rspec Gemfile.lock                                                                                                                5s 946ms
128:      bbq-rspec (= 0.4.0)
137:    bbq-rspec (0.4.0)
477:    rails_event_store-rspec (1.0.0)
478:      rspec (~> 3.0)
528:    rspec (3.9.0)
529:      rspec-core (~> 3.9.0)
530:      rspec-expectations (~> 3.9.0)
531:      rspec-mocks (~> 3.9.0)
532:    rspec-activemodel-mocks (1.1.0)
535:      rspec-mocks (>= 2.99, < 4.0)
536:    rspec-collection_matchers (1.2.0)
537:      rspec-expectations (>= 2.99.0.beta1)
538:    rspec-core (3.9.2)
539:      rspec-support (~> 3.9.3)
540:    rspec-expectations (3.9.1)
542:      rspec-support (~> 3.9.0)
543:    rspec-mocks (3.9.1)
545:      rspec-support (~> 3.9.0)
546:    rspec-rails (4.0.0)
550:      rspec-core (~> 3.9)
551:      rspec-expectations (~> 3.9)
552:      rspec-mocks (~> 3.9)
553:      rspec-support (~> 3.9)
554:    rspec-support (3.9.3)
805:  rails_event_store-rspec
816:  rspec-activemodel-mocks
817:  rspec-collection_matchers
818:  rspec-rails (~> 4.0)
```

I might be missing some crucial bit though.

**Comment by masylum** [comment]
I think you are right! Will triple check

**Comment by pawelpacana** [comment]
Please reopen if it is still the case.

**Pull request closed without merging**
