### PR TITLE
Evaled Gemfile does not work with dependabot

### PR DESCRIPTION
**Pull request by pawelpacana**
I'd very much like to use dependabot to bump dev dependencies,
especially with regard to rails and mutant versions used.

### CODE REVIEW

**Comment by mbj** [comment]
@pawelpacana Evaled dependencies work with Dependabot if you use `eval_gemfile 'literal-string-here'`.

**Comment by mbj** [comment]
You just have to avoid expressions. OT: I'd be happy to talk to the dependabot team to make a partial ruby evaluator that allows to use the common ideoms.

**Comment by pawelpacana** [comment]
I'll check that — easy to revert if it works as advertised ;)

**Comment by pawelpacana** [comment]
Seems to works, thanks @mbj!

**Pull request merged**
