### PR TITLE
Problem: some say fork rebase is hard

### PR DESCRIPTION
**Pull request by mpraglowski**
Solution: automate it

Instead of manually rebase your branch with `RailsEventStore/rails_event_store` repository just run: `make rebase`.
It will:
* remove git remote `upstream`
* add git remote `upstream` with link to main repository
* fetch master `branch` from `upstream`
* rebase your current branch with fetched `upstream/master`
* displays current status - hashed of last commits in `upstream/master`, `origin/master` & `HEAD` of current branch

### CODE REVIEW

**Comment by mpraglowski** [comment]
Results of `make rebase` on my branch with 2 commits (and merged local master):

```
~/arkency/rails_event_store$ make rebase
From github.com:RailsEventStore/rails_event_store
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream/master
Current branch active_job_dispatcher is up to date.
Everything up-to-date
Rebased with upstream/master
  upstream/master at 19cb821776cded94d29ab5d872d56ad876a6f830
  origin/master   at 6223378740bf4ef23a795013fc6967cd4a295a48
  current branch  at 7510d7a464034702b9496faf066f482bb358e9d9
```

You could check rebased history here https://github.com/mpraglowski/rails_event_store/commits/active_job_dispatcher

**Comment by mpraglowski** [comment]
Based on https://help.github.com/articles/syncing-a-fork/

**Comment by mlomnicki** [comment]
Seems useful to me. Should save a few keystrokes :+1:

**Comment by pawelpacana** [comment]
You could event extend it further with `make pr` with little help of https://hub.github.com

**Pull request merged**
